# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20160607_1234'),
        ('project', '0017_auto_20160603_1110'),
    ]

    operations = [
    ]
