# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-20 08:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160719_1259'),
        ('project', '0021_convert_static_to_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('public_id', models.CharField(default='', help_text='<CountryCode>-<uuid>-x-<ProjectID> eg: HU9fa42491x1', max_length=64)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('projects', project.models.ProjectManager()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='project_team', to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='project_viewers', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectdraft',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_draft', to='project.Project'),
        ),
        migrations.AddField(
            model_name='projectdraft',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='projectdraft_team', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectdraft',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='projectdraft_viewers', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectapproval',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='project.Project'),
        ),
        migrations.AddField(
            model_name='projectapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
