# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20171025_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdraft',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
