# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20171119_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalstrategy',
            options={'verbose_name_plural': 'Digital Strategies'},
        ),
    ]
