# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20171020_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapproval',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='project.Project'),
        ),
    ]
