# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20171115_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdraft',
            name='public_id',
        ),
    ]
