# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20171128_1133'),
        ('project', '0025_auto_20171124_1418'),
    ]

    operations = [
    ]
