# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_remove_projectdraft_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapproval',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
