# Generated by Django 2.1 on 2020-02-26 14:52

from django.db import migrations
from hashids import Hashids

def create_new_project_ids_based_on_hashids(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    Country = apps.get_model('country', 'Country')

    for project in Project.objects.exclude(public_id=''):
        project_country = Country.objects.filter(id=project.data['country']).first()
        if project_country:
            project.public_id = f"{project_country.code}{Hashids(min_length=8).encode(project.pk)}"
            project.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_auto_20200107_1328'),
    ]

    operations = [
        migrations.RunPython(create_new_project_ids_based_on_hashids, migrations.RunPython.noop),
    ]
