# Generated by Django 2.1 on 2020-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_new_project_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public_id',
            field=models.CharField(default='', help_text='<CountryCode><HashID> eg: HU9fa42491', max_length=64),
        ),
    ]
