# Generated by Django 2.1 on 2020-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20200228_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_fr', models.CharField(max_length=128, null=True)),
                ('name_es', models.CharField(max_length=128, null=True)),
                ('name_pt', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='research',
            field=models.NullBooleanField(),
        ),
    ]
