# Generated by Django 2.1 on 2020-04-08 08:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20200330_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelManagers(
            name='stage',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='tooltip',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
