# Generated by Django 2.1 on 2020-04-08 08:14

from django.db import migrations


def create_stages(apps, schema_editor):
    Stage = apps.get_model('project', 'Stage')

    stages = [
        {
            "order": 1,
            "name": "Opportunity and Ideation",
            "tooltip": "Interest in market engagement, desire to be considered in new national deployment environments",
        },
        {
            "order": 2,
            "name": "Preparation and Scoping",
            "tooltip": "Concept note, scoping template, top-level requirements written down, business case",
        },
        {
            "order": 3,
            "name": "Analysis and Design",
            "tooltip": "Project initiation doc, project charter, agreement on roles/respon, workplan, landscape "
                       "review, business requirements",
        },
        {
            "order": 4,
            "name": "Implementation Planning",
            "tooltip": "Data privacy, M&E plan, training needs, `stakeholder engagement",
        },
        {
            "order": 5,
            "name": "Developing or Adapting Solution",
            "tooltip": "External vendor adapting the product,  product owner tracks development, usual sprint cycle",
        },
        {
            "order": 6,
            "name": "Piloting and Evidence Generation",
            "tooltip": "Using new tool in the field, feeding back into iterative development, M&E with an eye towards "
                       "scale decision",
        },
        {
            "order": 7,
            "name": "Package and Advocacy",
            "tooltip": "Comms materials, demo, budget ask for scaling, indentify champions",
        },
        {
            "order": 8,
            "name": "Deploying",
            "tooltip": "(technology focused deployment issues) MNO agreements, SMS agreements, procurement of "
                       "mobiles/tablets, MDM, Deploying on Government Data Center, migration from legacy system",
        },
        {
            "order": 9,
            "name": "Scaling up",
            "tooltip": "train the trainers, M&E, bug documentation",
        },
        {
            "order": 10,
            "name": "Hand over or Complete",
            "tooltip": "capacity building of govt ICT for on-going maintenance",
        },
    ]

    for item in stages:
        Stage.objects.get_or_create(name_en=item['name'], **item)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_auto_20200408_0847'),
    ]

    operations = [
        migrations.RunPython(create_stages),
    ]
