# Generated by Django 2.1 on 2020-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_project_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='tooltip_ar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='tooltip_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='tooltip_es',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='tooltip_fr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='tooltip_pt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
