# Generated by Django 2.1 on 2020-04-08 09:32

from django.db import migrations


def tooltip_translation(apps, schema_editor):
    Stage = apps.get_model('project', 'Stage')
    for stage in Stage.objects.all():
        stage.tooltip_en = stage.tooltip
        stage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_auto_20200408_0930'),
    ]

    operations = [
        migrations.RunPython(tooltip_translation),
    ]
