# Generated by Django 2.1 on 2020-06-02 11:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0072_tooltip_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
