# Generated by Django 2.2.16 on 2021-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_auto_20210702_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='add_me_as_editor',
            field=models.BooleanField(default=False),
        ),
    ]
