# Generated by Django 4.2 on 2023-04-06 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_userprofile_odk_sync'),
        ('project', '0079_collection_add_me_as_editor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprojectapproval',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project approval', 'verbose_name_plural': 'historical project approvals'},
        ),
        migrations.AlterModelManagers(
            name='digitalstrategy',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='healthcategory',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='healthfocusarea',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hisbucket',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hscgroup',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='interoperabilitylink',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='interoperabilitystandard',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='licence',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stage',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='technologyplatform',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='coverageversion',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historicalprojectapproval',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectapproval',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectapproval',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Administrator who approved the project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='original_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='draft',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='odk_extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='research',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectimportv2',
            name='header_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='projectimportv2',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='research',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
