# Generated by Django 4.2 on 2023-04-21 15:16

from django.db import migrations


def decouple_platforms(apps, schema_editor):
    Project = apps.get_model('project', 'Project')

    counter = 0
    print('\n')

    data_fields = ['draft', 'data']

    for project in Project.objects.all():
        for field_name in data_fields:
            if 'platforms' in getattr(project, field_name) and getattr(project, field_name)['platforms']:
                software = []
                dhis = []
                for platform in getattr(project, field_name)['platforms']:
                    software.append(platform['id'])
                    dhis += platform['strategies']
                getattr(project, field_name)['software'] = list(set(software))
                getattr(project, field_name)['dhis'] = list(set(dhis))

                project.save(update_fields=[field_name])

                counter += 1
                print(f'Updated {counter} fields', end='\r', flush=True)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0080_alter_historicalprojectapproval_options_and_more'),
    ]

    operations = [
        migrations.RunPython(decouple_platforms, reverse_code=migrations.RunPython.noop),
    ]
