# Generated by Django 4.2.1 on 2023-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0081_decouple_platforms_into_software_dhis'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
