# Generated by Django 4.2.1 on 2023-05-19 20:24

from django.db import migrations
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0082_project_archived_projectversion_archived'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', project.models.ProjectManager()),
            ],
        ),
    ]
