# Generated by Django 4.2.3 on 2023-09-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0083_alter_project_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrow',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='project.projectimportv2'),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='project.project'),
        ),
    ]
