# Generated by Django 4.2.3 on 2023-07-25 12:03

import ckeditor.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project.cache


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0083_alter_project_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesAndApplicationsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('name_en', models.CharField(max_length=512, null=True)),
                ('name_fr', models.CharField(max_length=512, null=True)),
                ('name_es', models.CharField(max_length=512, null=True)),
                ('name_pt', models.CharField(max_length=512, null=True)),
                ('name_ar', models.CharField(max_length=512, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_fr', ckeditor.fields.RichTextField(null=True)),
                ('description_es', ckeditor.fields.RichTextField(null=True)),
                ('description_pt', ckeditor.fields.RichTextField(null=True)),
                ('description_ar', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Services and Application Types - Representations within the Digital Health Architecture',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServicesAndApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('name_en', models.CharField(max_length=512, null=True)),
                ('name_fr', models.CharField(max_length=512, null=True)),
                ('name_es', models.CharField(max_length=512, null=True)),
                ('name_pt', models.CharField(max_length=512, null=True)),
                ('name_ar', models.CharField(max_length=512, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_fr', ckeditor.fields.RichTextField(null=True)),
                ('description_es', ckeditor.fields.RichTextField(null=True)),
                ('description_pt', ckeditor.fields.RichTextField(null=True)),
                ('description_ar', ckeditor.fields.RichTextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_and_application_types', to='project.servicesandapplicationscategory')),
            ],
            options={
                'verbose_name_plural': 'Services and Application Types',
                'ordering': ['category__name', 'name'],
            },
            bases=(core.models.ParentByIDMixin, project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
