# Generated by Django 4.2.3 on 2023-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0084_alter_importrow_parent_alter_importrow_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='interoperabilitystandard',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Health Data Exchange Standards'), (2, 'Health Data Standardization'), (3, 'Demographic Data Standardization'), (4, 'Security & Privacy Standards'), (5, 'Technical Standards')], null=True),
        ),
    ]
