# Generated by Django 4.2.3 on 2023-07-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0084_servicesandapplicationscategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesandapplications',
            options={'ordering': ['category__name', 'id'], 'verbose_name_plural': 'Services and Application Types'},
        ),
    ]
