# Generated by Django 4.2.3 on 2023-07-26 15:24
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'services_and_application_types.json')


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0085_alter_servicesandapplications_options'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
