# Generated by Django 4.2.3 on 2023-09-19 09:04

from django.db import migrations, models
import django.db.models.manager
import project.cache


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0087_hscchallenge_description_hscchallenge_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSILicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('spdx_id', models.CharField(blank=True, max_length=64)),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'International'), (2, 'Non-Reusable'), (3, 'Other/Miscellaneous'), (4, 'Popular / Strong Community'), (5, 'Redundant with more popular'), (6, 'Special Purpose'), (7, 'Superseded'), (8, 'Uncategorized'), (9, 'Voluntarily retired')], null=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(project.cache.InvalidateCacheMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
