# Generated by Django 4.2.3 on 2023-09-19 09:24
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'osi_licenses.json')


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0088_osilicence'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
