version: "3"

services:
  django:
    restart: always
    build: ./django
    env_file:
      - ./django/.env
    links:
      - postgres
      - celery
      - redis
    volumes:
      - ./django:/src
      - ./nginx/site/static:/usr/share/django/static:rw
      - ./django/media:/usr/share/django/media:rw
      - log_data:/var/log/django
      - media_data:/src/media
    command: /usr/local/bin/gunicorn who_maps.wsgi:application -w 2 -b :8000 --reload --timeout 120
    # command: python manage.py runserver 0.0.0.0:8000  # FOR DEBUG

  celery:
    restart: always
    build: ./django
    env_file:
      - ./django/.env
    environment:
      - C_FORCE_ROOT=true
    links:
      - postgres
      - redis
    volumes:
      - ./django:/src
      - log_data:/var/log/django
    command: /usr/local/bin/celery -A scheduler worker -B -l info

  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/site:/usr/share/nginx/html:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django/media:/usr/share/nginx/html/media:rw
      - ./nginx/certs:/etc/letsencrypt:rw
      - ./nginx/certs-data:/data/letsencrypt:rw
    links:
      - django

  nuxt:
    restart: always
    build: ./frontend
    expose:
      - "3000"
    links:
      - django

  postgres:
    restart: always
    image: postgres:15.2-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7-bullseye

volumes:
  postgres_data:
  log_data:
  media_data:
