version: "3"

services:
    django:
        environment:
            - SITE_ID=2

    celery:
        environment:
            - SITE_ID=2
    nginx:
        volumes:
            - ./nginx/site:/usr/share/nginx/html:rw
            - ./nginx/conf.d_secure.dev:/etc/nginx/conf.d:ro
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/includes:/etc/nginx/includes:ro
            - ./django/media:/usr/share/nginx/html/media:rw
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        links:
            - django
            - nuxt
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
