django:
    environment:
        - SITE_ID=3

celery:
    environment:
        - SITE_ID=3

nginx:
  restart: always
  image: nginx:1.9.5
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/site:/usr/share/nginx/html:rw
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./nginx/ssl:/etc/nginx/ssl:ro
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./django/media:/usr/share/nginx/html/media:rw
  links:
    - django:django