django:
  restart: always
  build: ./django
  expose:
    - "8000"
  links:
    - postgres:postgres
    - celery:celery
    - rabbitmq:rabbitmq
  volumes:
    - ./django:/src
  command: /usr/local/bin/gunicorn who_maps.wsgi:application -w 2 -b :8000 --reload --timeout 120
#  command: python manage.py runserver 0.0.0.0:8000 # FOR DEBUG

celery:
  restart: always
  build: ./django
  environment:
    - C_FORCE_ROOT=true
  links:
    - postgres:postgres
    - rabbitmq:rabbitmq
  volumes:
    - ./django:/src
  command: /usr/local/bin/celery -A scheduler worker -B -l info

nginx:
  restart: always
  image: nginx:1.9.5
  ports:
    - "80:80"
  volumes:
    - ./nginx/site:/usr/share/nginx/html:rw
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./django/media:/usr/share/nginx/html/media:rw
  links:
    - django:django

postgres:
  restart: always
  image: postgres:9.5.1
  environment:
    - POSTGRESQL_DB=postgres
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASSWORD=postgres
  volumes_from:
    - postgresdata
  ports:
    - "5432:5432"

postgresdata:
  image: postgres:9.5.1
  volumes:
    - /var/lib/postgresql
  command: "/bin/true"

rabbitmq:
  restart: always
  image: rabbitmq:3.6.2
  environment:
    - RABBITMQ_PASS=mypass
  ports:
    - "5672:5672"
    - "15672:15672"
