version: "3"

services:
    django:
        environment:
            - SITE_ID=2

    celery:
        environment:
            - SITE_ID=2
    nginx:
        volumes:
        - ./nginx/site:/usr/share/nginx/html:rw
        - ./nginx/conf.d_secure:/etc/nginx/conf.d:ro
        - ./nginx/ssl:/etc/nginx/ssl:ro
        - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./django/media:/usr/share/nginx/html/media:rw
        - ./nginx/certs:/etc/letsencrypt:rw
        - ./nginx/certs-data:/data/letsencrypt:rw