# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-13 14:25
from __future__ import unicode_literals

from django.db import migrations

COUNTRIES = [{
    "model": "country.country",
    "pk": 33,
    "fields": {
      "created": "2017-03-10T12:47:57.529Z",
      "modified": "2017-03-10T13:25:41.883Z",
      "name": "afghanistan",
      "code": "AF"
    }
  },
  {
    "model": "country.country",
    "pk": 72,
    "fields": {
      "created": "2017-03-10T12:47:58.431Z",
      "modified": "2017-03-10T13:25:42.985Z",
      "name": "albania",
      "code": "AL"
    }
  },
  {
    "model": "country.country",
    "pk": 80,
    "fields": {
      "created": "2017-03-10T12:47:59.139Z",
      "modified": "2017-03-10T13:25:44.408Z",
      "name": "algeria",
      "code": "DZ"
    }
  },
  {
    "model": "country.country",
    "pk": 54,
    "fields": {
      "created": "2017-03-10T12:48:00.735Z",
      "modified": "2017-03-10T13:25:46.445Z",
      "name": "angola",
      "code": "AO"
    }
  },
  {
    "model": "country.country",
    "pk": 75,
    "fields": {
      "created": "2017-03-10T12:48:01.919Z",
      "modified": "2017-03-10T13:25:48.850Z",
      "name": "argentina",
      "code": "AR"
    }
  },
  {
    "model": "country.country",
    "pk": 58,
    "fields": {
      "created": "2017-03-10T12:48:04.858Z",
      "modified": "2017-03-10T13:25:52.087Z",
      "name": "armenia",
      "code": "AM"
    }
  },
  {
    "model": "country.country",
    "pk": 57,
    "fields": {
      "created": "2017-03-10T12:48:05.025Z",
      "modified": "2017-03-10T13:25:52.240Z",
      "name": "azerbaijan",
      "code": "AZ"
    }
  },
  {
    "model": "country.country",
    "pk": 49,
    "fields": {
      "created": "2017-03-10T12:58:36.088Z",
      "modified": "2017-03-10T13:25:52.598Z",
      "name": "bangladesh",
      "code": "BD"
    }
  },
  {
    "model": "country.country",
    "pk": 62,
    "fields": {
      "created": "2017-03-10T12:58:36.627Z",
      "modified": "2017-03-10T13:25:53.353Z",
      "name": "belarus",
      "code": "BY"
    }
  },
  {
    "model": "country.country",
    "pk": 14,
    "fields": {
      "created": "2017-03-10T12:58:37.362Z",
      "modified": "2017-03-10T13:25:54.124Z",
      "name": "benin",
      "code": "BJ"
    }
  },
  {
    "model": "country.country",
    "pk": 71,
    "fields": {
      "created": "2017-03-10T12:58:37.629Z",
      "modified": "2017-03-10T13:25:54.462Z",
      "name": "bhutan",
      "code": "BT"
    }
  },
  {
    "model": "country.country",
    "pk": 60,
    "fields": {
      "created": "2017-03-10T12:58:38.077Z",
      "modified": "2017-03-10T13:25:55.273Z",
      "name": "bolivia",
      "code": "BO"
    }
  },
  {
    "model": "country.country",
    "pk": 15,
    "fields": {
      "created": "2017-03-10T12:58:39.131Z",
      "modified": "2017-03-10T13:25:56.509Z",
      "name": "botswana",
      "code": "BW"
    }
  },
  {
    "model": "country.country",
    "pk": 21,
    "fields": {
      "created": "2017-03-10T12:58:40.680Z",
      "modified": "2017-03-10T13:25:59.715Z",
      "name": "brazil",
      "code": "BR"
    }
  },
  {
    "model": "country.country",
    "pk": 13,
    "fields": {
      "created": "2017-03-10T12:58:45.323Z",
      "modified": "2017-03-10T13:26:05.027Z",
      "name": "burkina-faso",
      "code": "BF"
    }
  },
  {
    "model": "country.country",
    "pk": 67,
    "fields": {
      "created": "2017-03-10T12:58:46.534Z",
      "modified": "2017-03-10T13:26:06.243Z",
      "name": "burundi",
      "code": "BI"
    }
  },
  {
    "model": "country.country",
    "pk": 64,
    "fields": {
      "created": "2017-03-10T12:58:46.972Z",
      "modified": "2017-03-10T13:26:06.845Z",
      "name": "c-te-d-ivoire",
      "code": "CI"
    }
  },
  {
    "model": "country.country",
    "pk": 22,
    "fields": {
      "created": "2017-03-10T12:58:47.630Z",
      "modified": "2017-03-10T13:26:07.692Z",
      "name": "cameroon",
      "code": "CM"
    }
  },
  {
    "model": "country.country",
    "pk": 77,
    "fields": {
      "created": "2017-03-10T12:58:48.188Z",
      "modified": "2017-03-10T13:26:08.338Z",
      "name": "cape-verde",
      "code": "CV"
    }
  },
  {
    "model": "country.country",
    "pk": 35,
    "fields": {
      "created": "2017-03-10T12:58:48.416Z",
      "modified": "2017-03-10T13:26:08.562Z",
      "name": "central-african-republic",
      "code": "CF"
    }
  },
  {
    "model": "country.country",
    "pk": 47,
    "fields": {
      "created": "2017-03-10T12:58:48.659Z",
      "modified": "2017-03-10T13:26:08.834Z",
      "name": "chad",
      "code": "TD"
    }
  },
  {
    "model": "country.country",
    "pk": 56,
    "fields": {
      "created": "2017-03-10T12:58:51.466Z",
      "modified": "2017-03-10T13:26:14.816Z",
      "name": "china",
      "code": "CN"
    }
  },
  {
    "model": "country.country",
    "pk": 23,
    "fields": {
      "created": "2017-03-10T12:59:02.131Z",
      "modified": "2017-03-10T13:26:27.122Z",
      "name": "congo-brazzaville",
      "code": "CG"
    }
  },
  {
    "model": "country.country",
    "pk": 41,
    "fields": {
      "created": "2017-03-10T12:59:03.082Z",
      "modified": "2017-03-10T13:26:28.080Z",
      "name": "congo-kinshasa",
      "code": "CD"
    }
  },
  {
    "model": "country.country",
    "pk": 26,
    "fields": {
      "created": "2017-03-10T12:59:05.552Z",
      "modified": "2017-03-10T13:26:30.266Z",
      "name": "costa-rica",
      "code": "CR"
    }
  },
  {
    "model": "country.country",
    "pk": 74,
    "fields": {
      "created": "2017-03-10T12:59:05.911Z",
      "modified": "2017-03-10T13:26:30.695Z",
      "name": "djibouti",
      "code": "DJ"
    }
  },
  {
    "model": "country.country",
    "pk": 70,
    "fields": {
      "created": "2017-03-10T12:59:06.010Z",
      "modified": "2017-03-10T13:26:30.803Z",
      "name": "egypt",
      "code": "EG"
    }
  },
  {
    "model": "country.country",
    "pk": 37,
    "fields": {
      "created": "2017-03-10T12:59:06.221Z",
      "modified": "2017-03-10T13:26:31.248Z",
      "name": "ethiopia",
      "code": "ET"
    }
  },
  {
    "model": "country.country",
    "pk": 27,
    "fields": {
      "created": "2017-03-10T12:59:06.859Z",
      "modified": "2017-03-10T13:26:31.888Z",
      "name": "gabon",
      "code": "GA"
    }
  },
  {
    "model": "country.country",
    "pk": 7,
    "fields": {
      "created": "2017-03-10T12:59:07.046Z",
      "modified": "2017-03-10T13:26:32.103Z",
      "name": "ghana",
      "code": "GH"
    }
  },
  {
    "model": "country.country",
    "pk": 73,
    "fields": {
      "created": "2017-03-10T12:59:07.366Z",
      "modified": "2017-03-10T13:26:32.562Z",
      "name": "guatemala",
      "code": "GT"
    }
  },
  {
    "model": "country.country",
    "pk": 25,
    "fields": {
      "created": "2017-03-10T12:59:07.912Z",
      "modified": "2017-03-10T13:26:33.486Z",
      "name": "guinea",
      "code": "GN"
    }
  },
  {
    "model": "country.country",
    "pk": 44,
    "fields": {
      "created": "2017-03-10T12:59:08.527Z",
      "modified": "2017-03-10T13:26:34.210Z",
      "name": "guinea-bissau",
      "code": "GW"
    }
  },
  {
    "model": "country.country",
    "pk": 53,
    "fields": {
      "created": "2017-03-10T12:59:08.833Z",
      "modified": "2017-03-10T13:26:34.611Z",
      "name": "haiti",
      "code": "HT"
    }
  },
  {
    "model": "country.country",
    "pk": 17,
    "fields": {
      "created": "2017-03-10T12:59:09.191Z",
      "modified": "2017-03-10T13:26:35.088Z",
      "name": "honduras",
      "code": "HN"
    }
  },
  {
    "model": "country.country",
    "pk": 31,
    "fields": {
      "created": "2017-03-10T12:59:09.983Z",
      "modified": "2017-03-10T13:26:36.356Z",
      "name": "india",
      "code": "IN"
    }
  },
  {
    "model": "country.country",
    "pk": 46,
    "fields": {
      "created": "2017-03-10T13:00:28.826Z",
      "modified": "2017-03-10T13:26:38.308Z",
      "name": "indonesia",
      "code": "ID"
    }
  },
  {
    "model": "country.country",
    "pk": 79,
    "fields": {
      "created": "2017-03-10T13:00:29.657Z",
      "modified": "2017-03-10T13:26:39.225Z",
      "name": "israel",
      "code": "IL"
    }
  },
  {
    "model": "country.country",
    "pk": 59,
    "fields": {
      "created": "2017-03-10T13:00:29.827Z",
      "modified": "2017-03-10T13:26:39.409Z",
      "name": "jamaica",
      "code": "JM"
    }
  },
  {
    "model": "country.country",
    "pk": 24,
    "fields": {
      "created": "2017-03-10T13:00:30.057Z",
      "modified": "2017-03-10T13:26:39.615Z",
      "name": "kenya",
      "code": "KE"
    }
  },
  {
    "model": "country.country",
    "pk": 2,
    "fields": {
      "created": "2017-03-10T13:00:30.275Z",
      "modified": "2017-03-10T13:26:40.005Z",
      "name": "liberia",
      "code": "LR"
    }
  },
  {
    "model": "country.country",
    "pk": 43,
    "fields": {
      "created": "2017-03-10T13:00:30.788Z",
      "modified": "2017-03-10T13:26:40.676Z",
      "name": "madagascar",
      "code": "MG"
    }
  },
  {
    "model": "country.country",
    "pk": 28,
    "fields": {
      "created": "2017-03-10T13:00:31.378Z",
      "modified": "2017-03-10T13:26:41.319Z",
      "name": "malawi",
      "code": "MW"
    }
  },
  {
    "model": "country.country",
    "pk": 32,
    "fields": {
      "created": "2017-03-10T13:00:31.682Z",
      "modified": "2017-03-10T13:26:41.817Z",
      "name": "malaysia",
      "code": "MY"
    }
  },
  {
    "model": "country.country",
    "pk": 63,
    "fields": {
      "created": "2017-03-10T13:00:32.072Z",
      "modified": "2017-03-10T13:26:42.285Z",
      "name": "maldives",
      "code": "MV"
    }
  },
  {
    "model": "country.country",
    "pk": 20,
    "fields": {
      "created": "2017-03-10T13:00:32.243Z",
      "modified": "2017-03-10T13:26:42.588Z",
      "name": "mali",
      "code": "ML"
    }
  },
  {
    "model": "country.country",
    "pk": 65,
    "fields": {
      "created": "2017-03-10T13:00:32.653Z",
      "modified": "2017-03-10T13:26:43.510Z",
      "name": "mauritania",
      "code": "MR"
    }
  },
  {
    "model": "country.country",
    "pk": 34,
    "fields": {
      "created": "2017-03-10T13:00:36.490Z",
      "modified": "2017-03-10T13:26:52.083Z",
      "name": "mexico",
      "code": "MX"
    }
  },
  {
    "model": "country.country",
    "pk": 6,
    "fields": {
      "created": "2017-03-10T13:00:50.150Z",
      "modified": "2017-03-10T13:27:25.203Z",
      "name": "morocco",
      "code": "MA"
    }
  },
  {
    "model": "country.country",
    "pk": 38,
    "fields": {
      "created": "2017-03-10T13:00:53.504Z",
      "modified": "2017-03-10T13:27:27.231Z",
      "name": "mozambique",
      "code": "MZ"
    }
  },
  {
    "model": "country.country",
    "pk": 5,
    "fields": {
      "created": "2017-03-10T13:00:53.934Z",
      "modified": "2017-03-10T13:27:28.038Z",
      "name": "myanmar",
      "code": "MM"
    }
  },
  {
    "model": "country.country",
    "pk": 51,
    "fields": {
      "created": "2017-03-10T13:00:54.593Z",
      "modified": "2017-03-10T13:27:29.130Z",
      "name": "namibia",
      "code": "NA"
    }
  },
  {
    "model": "country.country",
    "pk": 3,
    "fields": {
      "created": "2017-03-10T13:00:56.137Z",
      "modified": "2017-03-10T13:27:30.072Z",
      "name": "nepal",
      "code": "NP"
    }
  },
  {
    "model": "country.country",
    "pk": 42,
    "fields": {
      "created": "2017-03-10T13:00:56.836Z",
      "modified": "2017-03-10T13:27:31.279Z",
      "name": "nicaragua",
      "code": "NI"
    }
  },
  {
    "model": "country.country",
    "pk": 16,
    "fields": {
      "created": "2017-03-10T13:00:57.593Z",
      "modified": "2017-03-10T13:27:32.276Z",
      "name": "niger",
      "code": "NE"
    }
  },
  {
    "model": "country.country",
    "pk": 36,
    "fields": {
      "created": "2017-03-10T13:00:58.155Z",
      "modified": "2017-03-10T13:27:33.191Z",
      "name": "nigeria",
      "code": "NG"
    }
  },
  {
    "model": "country.country",
    "pk": 40,
    "fields": {
      "created": "2017-03-10T13:00:59.162Z",
      "modified": "2017-03-10T13:27:34.788Z",
      "name": "pakistan",
      "code": "PK"
    }
  },
  {
    "model": "country.country",
    "pk": 10,
    "fields": {
      "created": "2017-03-10T13:01:00.472Z",
      "modified": "2017-03-10T13:27:37.547Z",
      "name": "peru",
      "code": "PE"
    }
  },
  {
    "model": "country.country",
    "pk": 4,
    "fields": {
      "created": "2017-03-10T13:01:03.126Z",
      "modified": "2017-03-10T13:27:40.758Z",
      "name": "philippines",
      "code": "PH"
    }
  },
  {
    "model": "country.country",
    "pk": 39,
    "fields": {
      "created": "2017-03-10T13:01:03.869Z",
      "modified": "2017-03-10T13:27:41.512Z",
      "name": "rwanda",
      "code": "RW"
    }
  },
  {
    "model": "country.country",
    "pk": 18,
    "fields": {
      "created": "2017-03-10T13:01:04.158Z",
      "modified": "2017-03-10T13:27:41.884Z",
      "name": "sierra-leone",
      "code": "SL"
    }
  },
  {
    "model": "country.country",
    "pk": 55,
    "fields": {
      "created": "2017-03-10T13:01:05.230Z",
      "modified": "2017-03-10T13:27:44.106Z",
      "name": "south-africa",
      "code": "ZA"
    }
  },
  {
    "model": "country.country",
    "pk": 12,
    "fields": {
      "created": "2017-03-10T13:01:07.761Z",
      "modified": "2017-03-10T13:27:47.069Z",
      "name": "south-sudan",
      "code": "SS"
    }
  },
  {
    "model": "country.country",
    "pk": 11,
    "fields": {
      "created": "2017-03-10T13:01:08.183Z",
      "modified": "2017-03-10T13:27:47.421Z",
      "name": "sri-lanka",
      "code": "LK"
    }
  },
  {
    "model": "country.country",
    "pk": 45,
    "fields": {
      "created": "2017-03-10T13:01:08.380Z",
      "modified": "2017-03-10T13:27:47.829Z",
      "name": "sudan",
      "code": "SD"
    }
  },
  {
    "model": "country.country",
    "pk": 50,
    "fields": {
      "created": "2017-03-10T13:01:08.564Z",
      "modified": "2017-03-10T13:27:48.002Z",
      "name": "swaziland",
      "code": "SZ"
    }
  },
  {
    "model": "country.country",
    "pk": 8,
    "fields": {
      "created": "2017-03-10T13:01:08.970Z",
      "modified": "2017-03-10T13:27:48.818Z",
      "name": "tanzania",
      "code": "TZ"
    }
  },
  {
    "model": "country.country",
    "pk": 1,
    "fields": {
      "created": "2017-03-10T13:01:09.926Z",
      "modified": "2017-03-10T13:27:49.909Z",
      "name": "the-gambia",
      "code": "GM"
    }
  },
  {
    "model": "country.country",
    "pk": 30,
    "fields": {
      "created": "2017-03-10T13:05:15.067Z",
      "modified": "2017-03-10T13:27:49.954Z",
      "name": "togo",
      "code": "TG"
    }
  },
  {
    "model": "country.country",
    "pk": 29,
    "fields": {
      "created": "2017-03-10T13:05:54.146Z",
      "modified": "2017-03-10T13:27:50.195Z",
      "name": "tunisia",
      "code": "TN"
    }
  },
  {
    "model": "country.country",
    "pk": 61,
    "fields": {
      "created": "2017-03-10T13:05:55.066Z",
      "modified": "2017-03-10T13:27:51.830Z",
      "name": "turkey",
      "code": "TR"
    }
  },
  {
    "model": "country.country",
    "pk": 69,
    "fields": {
      "created": "2017-03-10T13:05:56.792Z",
      "modified": "2017-03-10T13:27:53.859Z",
      "name": "turkmenistan",
      "code": "TM"
    }
  },
  {
    "model": "country.country",
    "pk": 9,
    "fields": {
      "created": "2017-03-10T13:05:57.199Z",
      "modified": "2017-03-10T13:27:54.510Z",
      "name": "uganda",
      "code": "UG"
    }
  },
  {
    "model": "country.country",
    "pk": 82,
    "fields": {
      "created": "2017-03-10T13:06:00.622Z",
      "modified": "2017-03-10T13:27:56.688Z",
      "name": "ukraine",
      "code": "UA"
    }
  },
  {
    "model": "country.country",
    "pk": 66,
    "fields": {
      "created": "2017-03-10T13:15:07.937Z",
      "modified": "2017-03-10T13:28:04.993Z",
      "name": "united-states-of-america",
      "code": "US"
    }
  },
  {
    "model": "country.country",
    "pk": 68,
    "fields": {
      "created": "2017-03-10T13:15:22.144Z",
      "modified": "2017-03-10T13:28:23.157Z",
      "name": "uruguay",
      "code": "UY"
    }
  },
  {
    "model": "country.country",
    "pk": 78,
    "fields": {
      "created": "2017-03-10T13:15:22.846Z",
      "modified": "2017-03-10T13:28:23.757Z",
      "name": "uzbekistan",
      "code": "UZ"
    }
  },
  {
    "model": "country.country",
    "pk": 76,
    "fields": {
      "created": "2017-03-10T13:15:23.563Z",
      "modified": "2017-03-10T13:28:26.258Z",
      "name": "venezuela",
      "code": "VE"
    }
  },
  {
    "model": "country.country",
    "pk": 19,
    "fields": {
      "created": "2017-03-10T13:15:26.176Z",
      "modified": "2017-03-10T13:28:29.139Z",
      "name": "vietnam",
      "code": "VN"
    }
  },
  {
    "model": "country.country",
    "pk": 81,
    "fields": {
      "created": "2017-03-10T13:15:27.090Z",
      "modified": "2017-03-10T13:28:30.128Z",
      "name": "yemen",
      "code": "YE"
    }
  },
  {
    "model": "country.country",
    "pk": 52,
    "fields": {
      "created": "2017-03-10T13:15:27.500Z",
      "modified": "2017-03-10T13:28:30.314Z",
      "name": "zambia",
      "code": "ZM"
    }
  },
  {
    "model": "country.country",
    "pk": 48,
    "fields": {
      "created": "2017-03-10T13:15:27.793Z",
      "modified": "2017-03-10T13:28:30.746Z",
      "name": "zimbabwe",
      "code": "ZW"
    }
  }
]


def load_countries(apps, schema_editor):
    Country = apps.get_model("country", "Country")
    from operator import itemgetter
    countries = sorted(COUNTRIES, key=itemgetter('pk'))

    for country in countries:
        Country.objects.create(name=country['fields']['name'], code=country['fields']['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_remove_country_geodata'),
    ]

    operations = [
        migrations.RunPython(load_countries),
    ]
