# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-25 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0032_add_countries_senegal_eritrea_seychelles_saoTome'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map_version',
            field=models.IntegerField(default=0),
        ),
    ]
