# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0033_default_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'African Region'), (1, 'Region of the Americas'), (2, 'South-East Asia Region'), (3, 'European Region'), (4, 'Eastern Mediterranean Region'), (5, 'Western Pacific Region')], null=True),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_logos', to='country.Country'),
        ),
    ]
