# Generated by Django 2.0.7 on 2018-08-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0034_django2_20180711_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'African Region'), (1, 'Region of the Americas'), (2, 'South-East Asia Region'), (3, 'European Region'), (4, 'Eastern Mediterranean Region'), (5, 'Western Pacific Region')], null=True),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_logos', to='country.Country'),
        ),
    ]
