# Generated by Django 2.0.7 on 2018-08-04 11:30

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_django2_20180711_1501'),
        ('country', '0036_remove_country_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_text', models.TextField(blank=True, null=True)),
                ('footer_title', models.CharField(blank=True, max_length=128, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=128, null=True)),
                ('project_approval', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(blank=True, help_text='User who can update the donor', limit_choices_to={'user__groups__name': 'Country Admin'}, related_name='donor_admins', to='user.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Donors',
                'ordering': ('id',),
            },
            bases=(core.models.NameByIDMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DonorPartnerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_logos', to='country.Donor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
