# Generated by Django 2.0.7 on 2018-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0037_donor_donorpartnerlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
