# Generated by Django 2.1 on 2018-09-04 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0038_auto_20180904_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='code',
            field=models.CharField(default='NULL', help_text='Acronym for Donor', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
