# Generated by Django 2.0.7 on 2018-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0038_auto_20180804_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'African Region'), (1, 'Region of the Americas'), (2, 'South-East Asia Region'), (3, 'European Region'), (4, 'Eastern Mediterranean Region'), (5, 'Western Pacific Region')], null=True),
        ),
    ]
