# Generated by Django 2.1 on 2019-12-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0047_auto_20191216_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectureroadmapdocument',
            options={'ordering': ('id',)},
        ),
    ]
