# Generated by Django 2.1 on 2020-03-30 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('country', '0048_auto_20191219_1344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='architectureroadmapdocument',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='architectureroadmapdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='donor',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
