# Generated by Django 2.1 on 2020-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0049_auto_20200330_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
