# Generated by Django 4.2 on 2023-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_userprofile_odk_sync'),
        ('country', '0051_add_global_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='User who can write questionnaire', related_name='%(class)s_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='country',
            name='map_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='country',
            name='super_admins',
            field=models.ManyToManyField(blank=True, help_text='User who can update landing and all above', related_name='%(class)s_super_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User/viewer who can read confidential answers', related_name='%(class)s_viewers', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='countrycustomquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='User who can write questionnaire', related_name='%(class)s_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='super_admins',
            field=models.ManyToManyField(blank=True, help_text='User who can update landing and all above', related_name='%(class)s_super_admins', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User/viewer who can read confidential answers', related_name='%(class)s_viewers', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='donorcustomquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
