# Generated by Django 4.2 on 2023-04-18 17:58

from django.db import migrations


def remove_required_flag_from_custom_questions(apps, schema_editor):
    CountryCustomQuestion = apps.get_model('country', 'CountryCustomQuestion')
    DonorCustomQuestion = apps.get_model('country', 'DonorCustomQuestion')

    print(CountryCustomQuestion.objects.filter(required=True).update(required=False))
    print(DonorCustomQuestion.objects.filter(required=True).update(required=False))


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0052_alter_country_admins_alter_country_map_data_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_required_flag_from_custom_questions, migrations.RunPython.noop),
    ]
