# Generated by Django 4.2.1 on 2023-07-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0053_remove_required_flag_from_custom_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchitectureRoadMapDocument',
        ),
    ]
