# Generated by Django 4.2.3 on 2023-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0058_load_reference_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocumenttype',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Better eHealth ID'),
        ),
    ]
