# Generated by Django 4.2 on 2023-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0006_django2_20180711_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolkit',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='toolkitversion',
            name='data',
            field=models.JSONField(),
        ),
    ]
