# Generated by Django 4.2.3 on 2023-07-28 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_projectsearch_hfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsearch',
            name='hfa_categories',
        ),
        migrations.AddField(
            model_name='projectsearch',
            name='sapp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
