# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 13:14
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.sites.models import Site


def add_sites(apps, schema_editor):
    Site.objects.all().delete()
    site = Site.objects.create(domain="localhost", name="localhost")
    site = Site.objects.create(domain="dev.whomaps.pulilab.com", name="dev")
    site = Site.objects.create(domain="test.whomaps.pulilab.com", name="test")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sites),
    ]
