# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-20 12:07
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations

fixture = 'initial_groups'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_sites'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
