version: 2.1

orbs:
  jira: circleci/jira@1.1.0

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
          PGHOST: 127.0.0.1
          PGUSER: postgres
          DATABASE_URL: ''
          CI_RUN: True
          ODK_SYNC_ENABLED: False
      - image: circleci/postgres:10.9-alpine-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
      - image: circleci/node:12.13.0-stretch
      - image: circleci/redis:5-stretch
        environment:
          REDIS_URL: 127.0.0.1

    working_directory: ~/who-maps

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          keys:
          - v2-dependencies-f-{{ checksum "frontend/package.json" }}

      - restore_cache:
          keys:
          - v5-dependencies-b-{{ checksum "django/requirements.txt" }}

      - run:
          name: install frontend reqs
          working_directory: ~/who-maps/frontend
          command: |
            sudo npm -v
            sudo npm install

      - run:
          name: install mapshaper
          working_directory: ~/who-maps
          command: yarn global add mapshaper

      - run:
          name: install python reqs
          working_directory: ~/who-maps
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run pip install -r django/requirements.txt

      - save_cache:
          paths:
            - frontend/node_modules
          key: v2-dependencies-f-{{ checksum "frontend/package.json" }}

      - save_cache:
          paths:
            - ~/who-maps/venv
          key: v5-dependencies-b-{{ checksum "django/requirements.txt" }}

#      - run:
#          name: frontend unit tests
#          working_directory: ~/who-maps/frontend
#          command: yarn test

      - run:
          name: backend flake8
          working_directory: ~/who-maps/django
          command: pipenv run flake8

      - run:
          name: backend makemigrations
          working_directory: ~/megeni/django
          command: |
            pipenv run python manage.py makemigrations --noinput

      - run:
          name: backend migrations
          working_directory: ~/megeni/django
          command: |
            pipenv run python manage.py migrate

      - run:
          name: backend unit tests
          working_directory: ~/megeni/django
          command: |
            pipenv run py.test --full-trace --timeout=180 --cov --cov-report html --cov-fail-under 97 --cov-report term-missing --cov-config .coveragerc

      - run:
          name: backend check for commited migrations
          working_directory: ~/megeni/django
          command: |
            export TERM=xterm && ! git diff --name-status origin/master HEAD | grep /migrations/0
      - jira/notify:
          issue_regexp: '[A-Z0-9]{2,30}-[0-9]+'

  deploy:
    docker:
      - image: circleci/python:3.7.5-stretch
    working_directory: ~/who-maps
    steps:
      - checkout
      - run:
          name: Install fabric and pycrypto
          command: |
            pip install pycrypto
            pip install Fabric3==1.10.2.post3

      - run:
          name: Deploy Over SSH
          working_directory: ~/who-maps/django
          command: |
            fab dev deploy
          no_output_timeout: "20m"

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: development
          post-steps:
            - jira/notify:
                environment_type: development
                job_type: deployment
                issue_regexp: '[A-Z0-9]{2,30}-[0-9]+'
