# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: pulilab/who-maps-circleci
    working_directory: ~/who-maps

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-f-{{ checksum "frontend/package.json" }}
          - v1-dependencies-f-
      - restore_cache:
          keys:
          - v2-dependencies-b-{{ checksum "django/requirements.txt" }}
          - v2-dependencies-b-
      - run:
          working_directory: ~/who-maps/frontend
          command: yarn install

      - run:
          working_directory: ~/who-maps
          command: yarn global add mapshaper

      - run:
          working_directory: ~/who-maps/django
          command: pip3 install -r requirements.txt

      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-f-{{ checksum "frontend/package.json" }}
          paths:
            - /usr/local/lib/python3.6/dist-packages
          key: v2-dependencies-b-{{ checksum "django/requirements.txt" }}


      # run tests!

      - run:
          command: service postgresql start

      - run:
          working_directory: ~/who-maps/frontend
          command: yarn test

      - run:
          working_directory: ~/who-maps/django
          command: flake8

      - run:
          working_directory: ~/who-maps/django
          command: DATABASE_URL=localhost python3 manage.py migrate

      - run:
          working_directory: ~/who-maps/django
          command: DATABASE_URL=localhost CI_RUN=True py.test --cov --cov-report html --cov-fail-under 100 --cov-report term-missing --cov-config .coveragerc

