export const nameMapping = {
  name: 'Project Name',
  country: 'Country',
  donors: 'Investor',
  organisation: 'Organisation',
  geographic_scope: 'Geographic Scope',
  implementation_overview: 'Narrative of the project',
  start_date: 'Start Date',
  end_date: 'End Date',
  end_date_note: 'End Date Note',
  contact_name: 'Contact name',
  contact_email: 'Contact email',
  software: 'Software',
  health_focus_areas: 'Health Focus Areas',
  hsc_challenges: 'Health System Challenges',
  his_bucket: 'Health Information Systems',
  government_investor: 'Government Contribution',
  implementing_partners: 'Partners',
  implementing_team: 'Team',
  implementing_viewers: 'Viewers',
  implementation_dates: 'Technology Deployment Date',
  zero_cost: 'Zero cost license',
  codebase_accessible : 'Accessible codebase',
  is_customizable: 'Customizable software',
  free_replication : 'Allowed to replicate',
  osi_licenses : 'OSI license',
  repository: 'Link to Code documentation',
  wiki: 'Link to Wiki',
  mobile_application: 'Link to application',
  interoperability_links: 'Interoperability Links',
  interoperability_standards: 'Interoperability Standards',
  health_workers: 'Health Workers',
  clients: 'Clients',
  facilities: 'Facilities',
  sub_level: 'Coverage Type',
  digitalHealthInterventions: 'Digital Health Interventions'
}

export const importTemplate = [
  {
    'Project Name': 'MyProject',
    Country: 'Sierra Leone',
    Investor: 'Global Investor',
    Organisation: 'West African Health Organisation',
    'Geographic Scope': 'Gographipc Scope Free Text',
    'Narrative of the project': 'Narrative free text',
    'Start Date': '2019-10-04',
    'End Date': '2020-02-14',
    'Contact name': 'Nico',
    'Contact email': 'nico@pulilab.com',
    Software: 'Bamboo',
    'Digital Health Interventions': '3.4.1 Notify birth event|\n3.4.2 Register birth event',
    'Health Focus Areas': 'Adolescents and communicable diseases|\nOther sexual and reproductive health',
    'Health System Challenges': '1.1 Lack of population denominator|\n1.2 Delayed reporting of events',
    'Health Information Systems': 'A. Census, population information & data warehouse|\nB. Civil Registration and Vital Statistics',
    'Government Contribution': 'no they have not yet contributed',
    Partners: 'Partner_one|\nPartner two',
    Team: 'nico@pulilab.com|torben@pulilab.com',
    Viewers: 'nico@pulilab.com|torben@pulilab.com',
    'Technology Deployment Date': '2019-10-04',
    'Zero cost license': 'Yes',
    'Accessible codebase': 'Yes',
    'Customizable software': 'Yes',
    'Allowed to replicate': 'Yes',
    'OSI license': 'The MIT License|The Open Software License 3.0',
    'Link to Code documentation': 'http://www.valid.link.org',
    'Link to Wiki': 'http://www.valid.link.org',
    'Link to application': 'http://www.valid.link.org',
    'Interoperability Standards': 'ADX - Aggregate Data Exchange|\nCDA - Clinical Document Architecture',
    'Coverage Type': 'National Level',
    'Health Workers': 1,
    Clients: 2,
    Facilities: 3
  },
  {
    'Project Name': 'MyProject2',
    Country: 'Hungary',
    Investor: 'Barr Foundation|\nBergstrom Foundation',
    Organisation: 'Uni',
    'Geographic Scope': 'Gographipc Scope Free Text',
    'Narrative of the project': 'Narrative free text',
    'Start Date': '2019-10-04',
    'End Date': '2020-02-14',
    'Contact name': 'Nico',
    'Contact email': 'nico@pulilab.com',
    Software: 'Bamboo|\nOpenHIM',
    'Digital Health Interventions': '3.4.1 Notify birth event|\n3.4.2 Register birth event',
    'Health Focus Areas': 'Adolescents and communicable diseases|\nOther sexual and reproductive health',
    'Health System Challenges': '1.1 Lack of population denominator|\n1.2 Delayed reporting of events',
    'Health Information Systems': 'A. Census, population information & data warehouse|\nB. Civil Registration and Vital Statistics',
    'Government Contribution': 'no they have not yet contributed',
    Partners: 'Partner_one|\nPartner two',
    Team: 'nico@pulilab.com|torben@pulilab.com',
    Viewers: 'nico@pulilab.com|torben@pulilab.com',
    'Technology Deployment Date': '2019-10-04',
    'Zero cost license': 'Yes',
    'Accessible codebase': 'Yes',
    'Customizable software': 'Yes',
    'Allowed to replicate': 'Yes',
    'OSI license': 'The MIT License|The Open Software License 3.0',
    'Link to Code documentation': 'http://www.valid.link.org',
    'Link to Wiki': 'http://www.valid.link.org',
    'Link to application': 'http://www.valid.link.org',
    'Interoperability Standards': 'ADX - Aggregate Data Exchange|\nCDA - Clinical Document Architecture',
    'Coverage Type': 'National Level',
    'Health Workers': 1,
    Clients: 2,
    Facilities: 3
  }
]
