export const project_definition = {
  name: null,
  organisation: {
    id: undefined,
    name: ''
  },
  country: null,
  countryName: null,
  coverage: [{}],
  coverage_second_level: [{}],
  coverageType: 1,
  start_date: undefined,
  end_date: undefined,
  platforms: [{
    name: null,
    strategies: []
  }],
  licenses: [],
  fields: [],
  donors: [{}],
  application: [],
  reports: [{}],
  publications: [{}],
  links: [{}],
  contact_name: null,
  contact_email: null,
  implementation_overview: null,
  implementation_dates: null,
  geographic_scope: null,
  interoperability_links: [],
  interoperability_standards: [],
  wiki: '',
  repository: '',
  mobile_application: '',
  implementing_partners: [{}],
  data_exchanges: [],
  his_bucket: [],
  hsc_challenges: [],
  health_focus_areas: [],
  government_investor: undefined
};
