# Generated by Django 2.1 on 2020-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0068_auto_20200330_0934'),
        ('search', '0019_update_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('subject_en', models.CharField(max_length=200, null=True)),
                ('subject_fr', models.CharField(max_length=200, null=True)),
                ('subject_es', models.CharField(max_length=200, null=True)),
                ('subject_pt', models.CharField(max_length=200, null=True)),
                ('subject_ar', models.CharField(max_length=200, null=True)),
                ('receiver_type', models.CharField(choices=[('AU', 'All users'), ('APO', 'Project owners'), ('APOWP', 'Project owners with published projects')], default='AU', max_length=5)),
                ('message', models.TextField()),
                ('message_en', models.TextField(null=True)),
                ('message_fr', models.TextField(null=True)),
                ('message_es', models.TextField(null=True)),
                ('message_pt', models.TextField(null=True)),
                ('message_ar', models.TextField(null=True)),
                ('receivers_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
