project_structure = {
        "strategies": [
            "Client education and behavior change communication",
            "Client Information Systems",
            "Data Collection and Reporting",
            "Financial transactions and incentives",
            "Human resource management",
            "Point of care and diagnostics",
            "Provider training and education",
            "Service Delivery",
            "Supply management",
        ],
        "technology_platforms": [
            "Adobe Forms",
            "Bamboo",
            "Capatricy",
            "Commcare",
            "Crowd Map",
            "Data Winners",
            "DHIS2",
            "emocha",
            "Enketo",
            "Epi Collect",
            "FormHub",
            "Frontline SMS",
            "iFormBuilder",
            "IVR",
            "Kobo",
            "Kookoo",
            "Kujua",
            "Magpi",
            "Motech",
            "Muvuku",
            "ODK",
            "Ona",
            "OpenMRS",
            "OpenSRP",
            "OpenXData",
            "Pendragon",
            "REDcap",
            "RapidSMS",
            "RapidPro",
            "SMS",
            "Survey CTO",
            "Textit",
            "Usahidi",
            "USSD",
            "Voice"
        ],
        "licenses": [
            "Public domain",
            "Non protective free and open source software (e.g. Apache)",
            "Protective free and open source software",
            "Freemium",
            "Proprietary",
            "Other (to be justified)"
        ],
        "applications": [
            "Client education and behavior change communication",
            "Sensors point-of-care diagnostics",
            "Registries and vital events tracking",
            "Data collection and reporting",
            "Electronic health records",
            "Electronic decision support (e.g. protocols, algorithms, checklists)",
            "Provider-to-provider communication (e.g. user group, consultations)",
            "Provider work planning and scheduling",
            "Human resource management",
            "Supply chain management",
            "Financial transactions and incentives"
        ],
        "health_focus_areas": [
            "Child health",
            "Family Planning",
            "HIV/AIDS",
            "Infectious Diseases",
            "Malaria and other vector-borne diseases",
            "Maternal health",
            "Newborn heath",
            "Non Communicable Diseases",
            "Nutrition/Food Security",
            "Parasitic diseases",
            "Primary Care",
            "Sexual and Reproductive Health",
            "Tuberculosis",
            "Violence",
            "Water, Sanitation, and Hygiene"
        ],
        "interoperability_links": [
            "Yes, links to a client registry.",
            "Yes, links to digital HMIS.",
            "Yes, links to a health worker registry.",
            "Yes, links to eLMIS.",
            "Yes, links to digital laboratory information system.",
            "Yes, links to a facility registry.",
            "Yes, links to a Shared Health Record.",
            "Yes, links to a Terminology Service.",
            "Other"
        ],
        "interoperability_standards": [
            "ADX - Aggregate Data Exchange",
            "ATNA - Audit Trail and Node Authentication",
            "BPPC - Basic Patient Privacy Consents",
            "CDA - Clinical Document Architecture",
            "CSD - Care Services Discovery",
            "DICOM",
            "GS1",
            "HL7 v2",
            "HL7 v3",
            "HL7 FHIR Value Set & Sharing Value Sets (SVS)",
            "mACM - Mobile Alert Communication Management",
            "MHD - Mobile Access to Health Documents",
            "PIX or PIXm - (Mobile) Patient Identifier Cross Reference",
            "PDQ or PDQm - (Mobile) Patient Demographics Query",
            "SDMX - Statistical Data and Metadata Exchange",
            "XDS - Cross-Enterprise Document Sharing",
            "XUA - Cross-Enterprise User Assertion"
        ],
        "his_bucket": ["a", "b", "c"],
        "hsc_challenges": ["a", "b", "c"],
        "interventions": ["a", "b", "c"],
        "data_exchanges": ["a", "b", "c"]
}
