project_structure = {
    "licenses": [
        "Public domain",
        "Non protective free and open source software (e.g. Apache)",
        "Protective free and open source software",
        "Freemium",
        "Proprietary"
    ],
    "applications": [
        "Client education and behavior change communication",
        "Sensors point-of-care diagnostics",
        "Registries and vital events tracking",
        "Data collection and reporting",
        "Electronic health records",
        "Electronic decision support (e.g. protocols, algorithms, checklists)",
        "Provider-to-provider communication (e.g. user group, consultations)",
        "Provider work planning and scheduling",
        "Human resource management",
        "Supply chain management",
        "Financial transactions and incentives"
    ],
    "interoperability_standards": [
        "ADX - Aggregate Data Exchange",
        "ATNA - Audit Trail and Node Authentication",
        "BPPC - Basic Patient Privacy Consents",
        "CDA - Clinical Document Architecture",
        "CSD - Care Services Discovery",
        "DICOM",
        "GS1",
        "HL7 v2",
        "HL7 v3",
        "mACM - Mobile Alert Communication Management",
        "MHD - Mobile Access to Health Documents",
        "PIX or PIXm - (Mobile) Patient Identifier Cross Reference",
        "PDQ or PDQm - (Mobile) Patient Demographics Query",
        "SDMX - Statistical Data and Metadata Exchange",
        "XDS - Cross-Enterprise Document Sharing",
        "XUA - Cross-Enterprise User Assertion",
        "HL7 FHIR",
        "SVS - Sharing Value Sets",
        "GML Geography Markup Language",
        "XForms",
        "SNOMED",
        "ICD-10",
        "ISO 3166",
        "ISCO 08",
        "ISCO 88",
        "LOINC",
        "RxNORM",
        "CIEL"
    ],
    "his_bucket": [
        "Census, population information & data warehouse",
        "Civil Registration and Vital Statistics",
        "Client applications",
        "Client communication system",
        "Clinical terminology and classifications",
        "Community Information System",
        "EHR and health information repositories",
        "Electronic Medical Record",
        "Emergency response system",
        "Facility Management Information System",
        "Geographic Information Systems",
        "Health finance and insurance",
        "Health Management Information System",
        "Human Resource Information System",
        "Identification registries and directories",
        "Knowledge Management",
        "Laboratory and Diagnostic System",
        "Learning and Training System",
        "Logistics Management Information System",
        "Pharmacy System",
        "Public health and disease surveillance",
        "Research information system",
        "Data interchange interoperability and accessibility",
        "Environmental monitoring systems",
    ],
    "hsc_challenges": [
        {
            "name": "Information",
            "challenges": [
                "Lack of population denominator",
                "Delayed reporting of events",
                "Lack of quality/reliable data",
                "Communication roadblocks",
                "Lack of access to information or data",
                "Insufficient utilization of data and information",
                "Lack of unique identifiers"
            ]
        },
        {
            "name": "Availability",
            "challenges": [
                "Insufficient supply of commodities",
                "Insufficient supply of services",
                "Insufficient supply of equipment",
                "Insufficient supply of qualified health workers",
            ]
        },
        {
            "name": "Quality",
            "challenges": [
                "Poor patient experience",
                "Insufficient health worker competence",
                "Low quality of health commodities",
                "Insufficient continuity of care",
                "Insufficient supportive supervision",
                "Poor adherence to guidelines"
            ]
        },
        {
            "name": "Acceptability",
            "challenges": [
                "Lack of alignment with local norms",
                "Not addressing individual beliefs and practices",
            ]
        },
        {
            "name": "Utilization",
            "challenges": [
                "Low demand for services",
                "Geographic inaccessibility",
                "Low adherence to treatments",
                "Loss to follow-up",
            ]
        },
        {
            "name": "Efficiency",
            "challenges": [
                "Inadequate workflow management",
                "Lack of inappropriate referrals",
                "Poor planning and coordination",
                "Delayed provision of care",
                "Inadequate access to transportation",
                "Inadequate prioritization of clients",
            ]
        }
    ],
    "health_focus_areas": [
        {
            "name": "Red Group",
            "subGroups": [
                {"name": "TB", "health_focus_areas": ["TB: preventing infection",
                                                      "TB: stopping progression from infection to active disease",
                                                      "TB: treating active disease"]},
                {"name": "Sexually Transmitted Infections", "health_focus_areas": ["STI: Preventing Acquisition",
                                                                                   "STI: Preventing Transmission",
                                                                                   "STI: Preventing Complications"]},
                {"name": "HIV/AIDS Prevention and Treatment", "health_focus_areas": ["HIV: testing and diagnosis",
                                                                                     "HIV: Palliative Care",
                                                                                     "HIV: Prevention, Treatment of opportunistic infections",
                                                                                     "HIV: Antiretroviral therapy",
                                                                                     "HIV: Prevention"]},
                {"name": "Diarrheal Diseases", "health_focus_areas": ["Diarrheal Dis: Breastfeeding promotion",
                                                                      "Diarrheal Dis: Water supply and sanitation improvement",
                                                                      "Diarrheal Dis: Oral rehydration therapy",
                                                                      "Diarrheal Dis: Zinc"]},
                {"name": "Vaccine-Preventable Diseases", "health_focus_areas": ["Vaccine: national immunization program",
                                                                                "Vaccine: fixed facility",
                                                                                "Vaccine: campaign",
                                                                                "Vaccine: mobile",
                                                                                "Vaccine: outreach"]},
                {"name": "Malaria", "health_focus_areas": ["Malaria: Prompt access to effective treatment",
                                                           "Malaria: Provision of Insecticide treated nets",
                                                           "Malaria: Prevention and control of malaria in pregnant women",
                                                           "Malaria: Epidemic and emergency response",
                                                           "Malaria: Malaria vaccine",
                                                           "Malaria: Malaria prophylaxis treatment",
                                                           "Malaria: Residual spraying"]},
                {"name": "Tropical Diseases", "health_focus_areas": ["Chagas Disease",
                                                                     "Lymphatic Filariasis",
                                                                     "Onchocerciasis",
                                                                     "Leprosy", "Dengue", "Leishmaniasis", "African Trypanosomiasis"]},
                {"name": "Helminth Infections and Schistosomiasis", "health_focus_areas": ["Helminth: Anthelmintic Drug Treatment",
                                                                                           "Helminth: Improved Sanitation",
                                                                                           "Helminth: Health Education"]},
                {"name": "Acute Respiratory Infections in Children", "health_focus_areas": ["ARI: vaccines",
                                                                                            "ARI: case management"]},
                {"name": "Pregnancy, Maternal and Perinatal Conditions", "health_focus_areas": [ "Pregnancy: Fertility behaviour change",
                                                                                                 "Pregnancy: Infertility",
                                                                                                 "Pregnancy: Preconception care",
                                                                                                 "Pregnancy: Miscarriage",
                                                                                                 "Pregnancy: Abortion care",
                                                                                                 "Pregnancy: Male involvement",
                                                                                                 "Pregnancy: Immunizations",
                                                                                                 "Pregnancy: Malaria prevention",
                                                                                                 "Pregnancy: Hypertension and NCD screening"
                                                                                                 "Maternal: Fertility behavior change",
                                                                                                 "Maternal: Nutritional Interventions",
                                                                                                 "Maternal: Routine prenatal care at the primary level",
                                                                                                 "Maternal: Delivery care at the primary level",
                                                                                                 "Maternal: Postpartum care",
                                                                                                 "Maternal: Postabortion care",
                                                                                                 "Maternal: CEmOC package at the secondary level",
                                                                                                 "Maternal: Mental health screening"]},
                {"name": "Newborn", "health_focus_areas": ["Newborn: Prepregnancy health and nutrition",
                                                           "Newborn: Counseling and preparation for newborn care and breastfeeding",
                                                           "Newborn: Emergency preparedness",
                                                           "Newborn: Clean delivery at community level",
                                                           "Newborn: Simple early newborn care at community level",
                                                           "Newborn: Healthy home care including breastfeeding promotion, hygienic cord and skin care, thermal care, promotion of demand for quality care Newborn: Extra care of small babies and case management of pneumonia",
                                                           "Newborn: Prenatal care package",
                                                           "Newborn: Postnatal care to support healthy practices",
                                                           "Newborn: Early detection and referral of complications",
                                                           "Newborn: Skilled obstetric and immediate newborn care including resuscitation",
                                                           "Newborn: Emergency obstetric care to manage complications such as obstructed labor and hemorrhage",
                                                           "Newborn: Emergency newborn care for illness, especially sepsis management",
                                                           "Newborn: Extra care of very low birth weight babies including kangaroo mother care"]},
                {"name": "Stunting, Wasting, and Micronutrient Deficiency Disorders", "health_focus_areas": ["Nutrition: Promotion of Optimal Feeding of Infants and Young Children",
                                                                                                             "Nutrition: Vitamin A deficiency",
                                                                                                             "Nutrition: Iron deficiency",
                                                                                                             "Nutrition: Zinc deficiency",
                                                                                                             "Nutrition: Growth monitoring and counselling"]},
                {"name": "Cancer Control", "health_focus_areas": ["Cancer: Immunizations (e.g., HBV, HPV)",
                                                                  "Cancer: Tobacco Control",
                                                                  "Cancer: Alcohol Control",
                                                                  "Cancer: Dietary and Related Interventions",
                                                                  "Cancer: Pharmacological Interventions",
                                                                  "Cancer: Cancer Screening",
                                                                  "Cancer: Cancer Treatment and Palliative Care"]},
            ]
        },
        {
            "name": "Blue group",
            "subGroups": [
                {"name": "Diabetes", "health_focus_areas": ["Diabetes: prevention",
                                                            "Diabetes: screening",
                                                            "Diabetes: management"]},
                {"name": "Mental disorders", "health_focus_areas": ["Mental health screening",
                                                                    "Mental health management and treatment"
                                                                    ]},
                {"name": "Neurological Disorders", "health_focus_areas": ["Neurological Disorder Interventions"]},
                {"name": "Cardiovascular disease", "health_focus_areas": ["CVD Prevention",
                                                                          "CVD Treatment",
                                                                          "Long-Term Management of Existing Vascular Disease"]},
                {"name": "Respiratory Diseases of Adults", "health_focus_areas": ["Interventions for asthma",
                                                                                  "Interventions for COPD",
                                                                                  "Interventions for pneumonia and influenza"]},
                {"name": "Diseases of the Kidney and the Urinary System", "health_focus_areas": ["Hypertension interventions",
                                                                                                 "Kidney and urinary tract Screening"]},
                {"name": "Skin disease", "health_focus_areas": ["Skin disease Interventions"]},
                {"name": "Oral Health", "health_focus_areas": ["Oral health education and promotion",
                                                               "Oral health treatment"]},
                {"name": "Unintentional Injuries", "health_focus_areas": ["Road traffic injuries prevention",
                                                                          "Poisonings",
                                                                          "Fall-related injuries",
                                                                          "Burn-related injuries",
                                                                          "Drowning"]},
                {"name": "Interpersonal Violence", "health_focus_areas": ["Interpersonal violence: Prevention Strategies"
                                                                          "Interpersonal violence: Interventions"]},
            ]
        },
        {
            "name": "Green group",
            "subGroups": [
                {"name": "Water Supply, Sanitation, and Hygiene Promotion", "health_focus_areas": ["WASH: Safer Water",
                                                                                                   "WASH: Hand Washing",
                                                                                                   "WASH: Hygiene Education"
                                                                                                   ]},
                {"name": "Indoor Air Pollution", "health_focus_areas": ["Indoor pollution: Source of pollution",
                                                                        "Indoor pollution: Improve living environment",
                                                                        "Indoor pollution: User behaviors"]},
                {"name": "Outdoor Air and Water Pollution", "health_focus_areas": ["Outdoor: Interventions to Reduce Air Pollution",
                                                                                   "Outdoor: Interventions to Reduce Water Pollution"]},
                {"name": "Diet and Lifestyle Changes to prevent chronic disease", "health_focus_areas": ["Lifestyle: Avoid smoking",
                                                                                                         "Lifestyle: Pursue physical activity",
                                                                                                         "Lifestyle: Avoid overweight",
                                                                                                         "Lifestyle: Educational Interventions",
                                                                                                         "Lifestyle: Worksite Interventions",
                                                                                                         "Lifestyle: Interventions by Health Care Providers",
                                                                                                         "Lifestyle: Promote Walking and Bicycle Riding",
                                                                                                         "Lifestyle: Promoting Healthy Food Choices"]},
                {"name": "Risk from High Blood Pressure, Cholesterol, and Bodyweight", "health_focus_areas": ["Risk: Interventions to Reduce Bodyweight",
                                                                                                              "Risk: Healthy diet (low sodium, high potassium",
                                                                                                              "Risk: Physical activity",
                                                                                                              "Risk: Medications to lower blood pressure"]},
                {"name": "Tobacco Addiction", "health_focus_areas": ["Tobacco: Smoking cessation treatment",
                                                                     "Tobacco: Reducing exposure to passive tobacco smoke",
                                                                     "Tobacco: Preventing initiation among youths and young adults"
                                                                     ]},
                {"name": "Alcohol", "health_focus_areas": ["Alcohol: Education sessions and psychosocial counseling",
                                                           "Alcohol: Population-wide measures"
                                                           ]},
                {"name": "Illicit drug use", "health_focus_areas": ["Illicit drug: Prevention including education",
                                                                    "Illicit drug: Voluntary Treatment",
                                                                    "Illicit drug: Involuntary Treatment"
                                                                    ]}
            ]
        },
        {
            "name": "Orange Group",
            "subGroups": [
                {"name": "Learning and Developmental Disabilities", "health_focus_areas": ["Learning Disability: Primary prevention to control the underlying cause or condition",
                                                                                           "Learning Disability: Preventing an existing illness or injury from progressing to long-term disability",
                                                                                           "Learning Disability: Rehabilitation and special educational services"]},
                {"name": "Loss of Vision and Hearing", "health_focus_areas": ["Childhood Blindness",
                                                                              "Cataract interventions",
                                                                              "Trachoma interventions",
                                                                              "Onchocerciasis interventions",
                                                                              "Hearing loss screening programs",
                                                                              "Hearing loss education",
                                                                              "Hearing loss surgery",
                                                                              "Hearing loss medications",
                                                                              "Hearing loss assistive devices"]},
                {"name": "Interventions for Musculoskeletal Conditions", "health_focus_areas": ["Musculoskeletal: Preventive strategies",
                                                                                                "Musculoskeletal: Screening",
                                                                                                "Musculoskeletal: Symptomatic treatments",
                                                                                                "Musculoskeletal: Rheumitoid Arthritis",
                                                                                                "Musculoskeletal: Osteoporosis"]},
                {"name": "Pain Control", "health_focus_areas": ["Pain: Opioid treatment",
                                                                "Pain: Non-Opioid treatments and strategies"]},
            ]
        },
        {
            "name": "Group bordeaux",
            "subGroups": [
                {"name": "Contraceptives", "health_focus_areas": ["Counseling",
                                                                  "Permanent and Long-Term Methods",
                                                                  "Temporary Methods", "Emergency Contraception",
                                                                  "Social Marketing"]},
                {"name": "Health of Adolescents and Youth", "health_focus_areas": ["School - Based Health and Nutrition Programs",
                                                                                   "Youth Friendly Facilities",
                                                                                   "Life - skills and health and sexuality education",
                                                                                   "Peer education",
                                                                                   "Mass media and community mobilization",
                                                                                   "Youth development programs",
                                                                                   "Social marketing",
                                                                                   "Workplace and private sector programs"
                                                                                   ]},
                {"name": "Integrated Management of the Sick Child (integrated approaches to diarrhea, malaria, pneumonia, measles, other severe infections, and malnutrition)",
                 "health_focus_areas": ["IMNCI: Improve Health Worker Performance (assess signs and symptoms, classify illness, and provide appropriate treatment and education)",
                                        "IMNCI: Improve Health Systems (improve drug availability, effective supervision, referral services, and health information systems)",
                                        "IMNCI: Improve Family and Community Practices (prevent illness, home treatment of infections, improve care-seeking practices and compliance with treatment)"]},
                {"name": "Occupational Health", "health_focus_areas": ["Occupational: Strategies for Improving Working Conditions",
                                                                       "Occupational: Improvement of Access to Health Care",
                                                                       "Occupational: Surveillance and Reporting"]},
                {"name": "Natural Disaster Mitigation and Relief", "health_focus_areas": ["Disaster: Assessment of the Health Situation",
                                                                                          "Disaster: Mass Casualties Treatment",
                                                                                          "Disaster: Strengthened Surveillance, Prevention, and Control of CommunicableDiseases",
                                                                                          "Disaster: Environmental Health",
                                                                                          "Disaster: Transparent Management of Donations and Supplies",
                                                                                          "Disaster: Coordination of the Humanitarian Health Effort",
                                                                                          "Disaster: Emergency Preparedness of the Health Sector",
                                                                                          "Disaster: Prevention and Mitigation"]},
                {"name": "Emergency Medical Services", "health_focus_areas": ["EMS: Paramedics",
                                                                              "EMS: Lay response",
                                                                              "EMS: Transportation and communication systems",
                                                                              "EMS: Ambulatory systems"]}
            ]
        }
    ]
}
