# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160719_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
