# Generated by Django 2.1 on 2020-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190312_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_toolkit_digest_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_approval_request_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project_updates_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_request_notification',
            field=models.BooleanField(default=True),
        ),
    ]
