# Generated by Django 2.1 on 2020-04-17 14:34
from django.db import migrations


def update_email_changes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, c = Group.objects.get_or_create(name='Email Address Updater')
    user_content_type = ContentType.objects.get(app_label='auth', model='user')
    permission = Permission.objects.get(content_type=user_content_type, codename='change_user')
    group.permissions.add(permission)

    try:
        user = User.objects.get(email='maeghan.orton@gmail.com')
    except User.DoesNotExist:
        pass
    else:
        user.is_staff = True
        user.save()
        group.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200210_1252'),
    ]

    operations = [
        migrations.RunPython(update_email_changes),
    ]
