# Generated by Django 4.2 on 2023-04-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='odk_sync',
        ),
    ]
