# Generated by Django 4.2 on 2023-04-12 08:05
from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.models import Q
from django.utils.crypto import get_random_string


def set_password_for_invited_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    users = User.objects.filter(Q(is_active=True), Q(password__startswith='!') | Q(password__isnull=True))
    print(f"Setting password for {users.count()} users...")
    for user in users:
        user.password = make_password(get_random_string(length=10))
        user.userprofile.invited = True
        user.userprofile.save()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_userprofile_invited'),
    ]

    operations = [
        migrations.RunPython(set_password_for_invited_users, reverse_code=migrations.RunPython.noop),
    ]
