# Generated by Django 2.2.16 on 2021-08-05 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpiexport', '0005_auto_20210723_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogprojectstatus',
            name='draft',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
