# Generated by Django 2.2.16 on 2021-09-23 08:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0051_add_global_country'),
        ('kpiexport', '0006_auditlogprojectstatus_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogDataStandards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='WARNING: Only use the year and month of this')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('standards', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'verbose_name': 'Data Standards KPI',
                'verbose_name_plural': 'Data Standards KPIs',
            },
        ),
    ]
