# Generated by Django 2.2.16 on 2021-09-29 14:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0051_add_global_country'),
        ('kpiexport', '0007_auditlogdatastandards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogHFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='WARNING: Only use the year and month of this')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hfa', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'verbose_name': 'Health Focus Areas KPI',
                'verbose_name_plural': 'Health Focus Areas KPIs',
            },
        ),
        migrations.CreateModel(
            name='AuditLogHealthCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='WARNING: Only use the year and month of this')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('categories', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
            options={
                'verbose_name': 'Health Categories KPI',
                'verbose_name_plural': 'Health Categories KPIs',
            },
        ),
    ]
